language: python

python:
  - '2.7'

install:
  - pip install --requirement requirements.txt
  - pip install coveralls

script:
  - coverage run --source='./txstripe' $(which trial) txstripe && coverage report --show-missing
  - flake8 txstripe/.

after_success:
  - coveralls
